name: sha_per
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  mongo_dart: ^0.10.0
  shared_preferences: ^2.2.2
  js: ^0.7.0
  http: ^0.13.3
  shelf: ^1.4.1
  http_server: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
